spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/db
  profiles:
    active: default

  mail:
    host: smtp.gmail.com
    port: 587
    username: cdpl4ter@gmail.com
    password: tyatgaqfjkfueqyf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


app:
  cors:
    allowed-origins: http://localhost:8080
  init-db: false
  seed-dir: backend/src/main/resources/seeds


server:
  port: 8080
  forward-headers-strategy: native