spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/db
  profiles:
    active: default

  security:
    oauth2:
      client:
        registration:
          ccc:
            client-Id: fdb53ef1-b2d0-4f6c-afad-406a0d15bd41
            client-Secret: m518Q~c2Zz3n5Vj_oKmfLP2lCk-UQ3DTvwVBFb7z
            redirect-uri: http://localhost:9191/login/oauth2/code/ccc
            scope: "https://graph.microsoft.com/.default"
            client-name:
        provider:
          ccc:
            issuer-uri: https://login.microsoftonline.com/81b9b473-132d-4efa-b355-55ca32482817/v2.0
            authorization-Uri: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
            token-Uri: https://login.microsoftonline.com/common/oauth2/v2.0/token
            user-Info-Uri: https://graph.microsoft.com/oidc/userinfo


app:
  cors:
    allowed-origins: http://localhost:8080
  init-db: false
  seed-dir: backend/src/main/resources/seeds


server:
  port: 9191
  forward-headers-strategy: native