spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/db
    redis:
      host: localhost
      port: 6379
  profiles:
    active: default

  mail:
    host: smtp.gmail.com
    port: 587
    username: cdpl4ter@gmail.com
    password: tyatgaqfjkfueqyf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  tokenName: "accessToken"
  secret: "5CE74751FAF5ED2877C51A93021368E0FD3C954444CF1F7136720388EE100998"
  exp: 86400 # 24 hours

app:
  init-db: false
  seed-dir: backend/src/main/resources/seeds


server:
  port: 8080
  forward-headers-strategy: native