spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/db}
      database: db
  profiles:
    active: default
  cache:
    type: redis

  mail:
    host: smtp.gmail.com
    port: 587
    username: cdpl4ter@gmail.com
    password: tyatgaqfjkfueqyf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  tokenName: "accessToken"
  secret: ${JWT_SECRET:5CE74751FAF5ED2877C51A93021368E0FD3C954444CF1F7136720388EE100998}
  exp: 86400 # 24 hours

app:
  init-db: false
  seed-dir: backend/src/main/resources/seeds


server:
  port: 8080
  forward-headers-strategy: native